<a href="https://colab.research.google.com/github/Taheri1400/machine-learning-projects/blob/main/bank_marketing_solved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
بازاریابی بانکی
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مقدمه
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    بازاریابی یکی از ستون‌های اصلی هر کسب‌و‌کاری است. بازاریابی است که به افزایش سود و گسترش سازمان کمک می‌کند. در بازاریابی سعی می‌کنیم مخاطبان خود را به محصولی که قصد فروشش را داریم جذب کنیم، تا به این گونه فروش را افزایش دهیم.
    بازاریابی هوشمند، یکی از کاربردهای هوش مصنوعی و یادگیری ماشین در تجارت و کسب‌و‌کار است. یکی از اساس بازاریابی هوشمند را در جمله زیر می‌بینیم.
    <br>
    <i>«محصول را به کسانی معرفی کنیم که به احتمال بیشتری خرید انجام می‌دهند.»</i>
    <br>
    مجموعه‌داده‌ای که در اختیار داریم، شامل اطلاعات مختلف از مشتریانی است که مخاطب یک کمپین بازاریابی برای سپرده بلندمدت بانکی بوده‌اند.
    کمپین بازاریابی یا پویش بازاریابی، مجموعه فعالیت‌هایی است که آگاهی مشتریان را نسبت به یک محصول افزایش می‌دهد.
    <br>
     در مورد بازاریابی بانکی می‌توان این‌گونه تعریف کرد که متخصصان بازاریابی بانکی، با روش‌های متنوع سعی در افزایش آگاهی مشتریان درمورد خدمات بانکی دارند.
    در این مسئله نیز ما اطلاعات مختلفی از مشتریان یک بانک را در اختیار داریم. همچنین می‌دانیم نتیجه‌ی کمپین‌های قبلی مارکتینگ برای آن‌ها چگونه بوده است. بنابراین قصد داریم به روش‌های هوشمند پیش‌بینی کنیم کدام مشتر‌ی‌ها، برای سپرده‌‌ی بلندمدتی که تحت کمپین جدید است، اقدام می‌کنند. به عبارت بهتر، می‌خواهیم بدانیم نتیجه‌ی کمپین جدید، برای کدام مشتری موفقیت‌آمیز خواهد بود.
    از آن جایی که هنوز با مدل‌سازی آشنا نشده‌اید صرفاً از شما می‌خواهیم در پیش‌پردازش داده‌ها به ما کمک کنید. کدهای مرتبط با مدل‌سازی داخل همین نوت‌بوک وجود دارند. شما فقط کافیست آن‌ها را اجرا کنید!
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
     مجموعه‌داده‌ای که در این سوال در اختیار داریم، همانطور که پیش‌تر گفته شد، اطلاعات مشتریانی را به دست می‌دهد که تحت کمپین معرفی سپرده بلندمدت بانک، با آن‌ها تماس گرفته شده است. بنابراین هر سطر از مجموعه‌داده، مربوط به یک مشتری است. در جدول زیر، ستون‌های این مجموعه‌داده را بررسی می‌کنیم.
<br>    
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
        
|ستون| توضیحات|
| :------: | :-------: |
| <code>age</code> | سن مشتری |
| <code>job</code> | شغل مشتری |
| <code>marital</code> | وضعیت تاهل مشتری |
| <code>education</code> | وضعیت تحصیلی مشتری |
| <code>default</code> | وضعیت نکول* (عدم پرداخت بدهی) |
| <code>housing</code> | آیا مشتری وام مسکن گرفته است |
| <code>loan</code> | آیا مشتری وام شخصی گرفته است |
| <code>is_telephone_contact</code> | آیا تماس با مشتری از طریق تلفن ثابت بوده است |
| <code>month</code> | ماهی که آخرین تماس با مشتری گرفته شده است |
| <code>day_of_week</code> | روزی از هفته که آخرین تماس با مشتری گرفته شده است |
| <code>duration</code> | مدت زمانی که آخرین تماس با مشتری به طول انجامیده است |
| <code>campaign</code> | تعداد دفعات تماسی که با همین مشتری در همین کمپین گرفته شده است |
| <code>pdays</code> | تعداد روزی که از آخرین تماس با مشتری برای کمپین قبلی می‌گذرد. اگر ۹۹۹ باشد، یعنی در کمپین قبلی با این مشتری تماس گرفته نشده است |
| <code>previous</code> | تعداد تماس‌هایی که تا قبل از این کمپین با این مشتری برقرار شده است |
| <code>poutcome</code> | نتیجه کمپین قبلی برای این مشتری |
| <code>y</code> | نتیجه کمپین فعلی برای این مشتری |

*:
0: مشتری بدهی خود را به‌موقع پرداخت کرده و نکول نکرده است.
1: مشتری در پرداخت بدهی خود نکول کرده است (یعنی قادر به پرداخت اقساط یا بدهی‌های خود نبوده است).
</font>
</div>
<center>

<br>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    بنابراین در مجموع این مجموعه‌داده دارای ۱۶ ستون و ۴۱۱۸۸ سطر است.
    <br>
    در این مجموعه‌داده مقادیر گم‌شده با عبارت <code>unknown</code> مشخص شده‌اند. یعنی هر جا کلمه‌ی <code>unknown</code> دیده شد، به منزله‌ی <code>NaN</code> است. پرکردن مقادیر گم‌شده هم بخشی از حل مسئله است که در ادامه کامل‌تر به آن پرداخته‌ایم.
<br>    
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    حال که قرار است در پیش‌پردازش داده به ما کمک کنید، از شما می‌خواهیم مقادیر گسسته و دسته‌ای مجموعه‌داده را مدیریت کنید. برای آن‌که بتوانید مقادیر گسسته را به عدد تبدیل کنید، نیاز است جدول راهنمایی داشته باشید. در زیر ۵ جدول تبدیل آورده شده است که به کمک آن‌ها می‌توانید مدیریت ستون‌های دسته‌ای را بهتر انجام دهید.
<br>    
</font>
</p>


<center>
<div style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
        
|مقادیر درون دیتافریم|مقادیری که باید جایگزین بشوند|
| :---: | :---: |
|<code>yes</code>|<code>1</code>|
|<code>no<code>|<code>0</code>|
        
<br>

|مقادیر درون دیتافریم|مقادیری که باید جایگزین بشوند|
| :---: | :---: |
|<code>illiterate</code>|<code>0</code>|
|<code dir=ltr>basic.4y</code>|<code>1</code>|
|<code dir=ltr>basic.6y</code>|<code>2</code>|
|<code dir=ltr>basic.9y</code>|<code>3</code>|
|<code dir=ltr>high.school</code>|<code>4</code>|
|<code dir=ltr>professional.course</code>|<code>5</code>|
|<code dir=ltr>university.degree</code>|<code>6</code>|
        
<br>

|مقادیر درون دیتافریم|مقادیری که باید جایگزین بشوند|
| :---: | :---: |
|<code>mon</code>|<code>0</code>|
|<code>tue</code>|<code>1</code>|
|<code>wed</code>|<code>2</code>|
|<code>thu</code>|<code>3</code>|
|<code>fri</code>|<code>4</code>|
|<code>sat</code>|<code>5</code>|
|<code>sun</code>|<code>6</code>|

<br>

|مقادیر درون دیتافریم|مقادیری که باید جایگزین بشوند|
| :---: | :---: |
|<code>jan</code>|<code>0</code>|
|<code>feb</code>|<code>1</code>|
|<code>mar</code>|<code>2</code>|
|<code>apr</code>|<code>3</code>|
|<code>may</code>|<code>4</code>|
|<code>jun</code>|<code>5</code>|
|<code>jul</code>|<code>6</code>|
|<code>aug</code>|<code>7</code>|
|<code>sep</code>|<code>8</code>|
|<code>oct</code>|<code>9</code>|
|<code>nov</code>|<code>10</code>|
|<code>dec</code>|<code>11</code>|

<br>

|مقادیر درون دیتافریم|مقادیری که باید جایگزین بشوند|
| :---: | :---: |
|<code>failure</code>|<code dir=ltr>-1</code>|
|<code>nonexistent</code>|<code dir=ltr>0</code>|
|<code>success</code>|<code dir=ltr>1</code>|
        
        
</font>
</div>
</center>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    کتابخانه‌های مورد نیاز را وارد کرده و مجموعه‌داده را بخوانید.
<br>    
</font>
</p>

In [ ]:
!pip install numpy==1.26.4

# Install FLAML with AutoML features
!pip install "flaml[automl]"

# Now import required libraries
import pandas as pd
import numpy as np  # Always use np.nan (lowercase 'n')

from flaml import AutoML
from sklearn.metrics import f1_score

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.11/dist-packages (1.26.4)
Requirement already satisfied: flaml[automl] in /usr/local/lib/python3.11/dist-packages (2.3.5)
Requirement already satisfied: NumPy>=1.17 in /usr/local/lib/python3.11/dist-packages (from flaml[automl]) (1.26.4)
Requirement already satisfied: lightgbm>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from flaml[automl]) (4.5.0)
Requirement already satisfied: xgboost<3.0.0,>=0.90 in /usr/local/lib/python3.11/dist-packages (from flaml[automl]) (2.1.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from flaml[automl]) (1.15.3)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.11/dist-packages (from flaml[automl]) (2.2.2)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from flaml[automl]) (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->flaml[automl]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->flaml[automl]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.4->flaml[automl]) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0.0->flaml[automl]) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0.0->flaml[automl]) (3.6.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.11/dist-packages (from xgboost<3.0.0,>=0.90->flaml[automl]) (2.21.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.4->flaml[automl]) (1.17.0)

In [ ]:
from google.colab import files
uploaded=files.upload()
df=pd.read_csv('bank-additional-full.csv', low_memory=False, na_values=['unknown'])
df.head()

Saving bank-additional-full.csv to bank-additional-full (4).csv

,age,job,marital,education,default,housing,loan,is_telephone_contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,y
0,56,housemaid,married,basic.4y,no,no,no,yes,may,mon,261,1,999,0,nonexistent,no
1,57,services,married,high.school,NaN,no,no,yes,may,mon,149,1,999,0,nonexistent,no
2,37,services,married,high.school,no,yes,no,yes,may,mon,226,1,999,0,nonexistent,no
3,40,admin.,married,basic.6y,no,no,no,yes,may,mon,151,1,999,0,nonexistent,no
4,56,services,married,high.school,no,no,yes,yes,may,mon,307,1,999,0,nonexistent,no


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    برای آن که ارزش کار خود را درک کنید، می‌توانید ابتدا که هیچ‌گونه پیش‌پردازشی روی داده انجام نشده است، یکبار با داده‌های اصلی مدل‌سازی کرده و عملکرد مدل را مشاهده کنید. با اجرای سلول زیر یک مدل روی داده‌ها آموزش می‌بیند و نتایجی تولید می‌کند. توجه کنید که اجرای این سلول و فرآیند مدل‌سازی ممکن است چند دقیقه‌ای طول بکشد.
    <br>
    اگر اجرای این سلول با شکست مواجه شد، می‌تواند به یکی از دلایل زیر باشد.
</font>
</p>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    <ul>
        <li>
            کتابخانه‌ی Fast Auto ML را نصب نکرده باشید.
        </li>
        <li>
            در بارگیری مجموعه‌داده دچار مشکل شده باشید.
        </li>
    </ul>
</font>
</div>

In [ ]:
target_variable = 'y'
df_train = df.sample(frac=.7, random_state=313)

model = AutoML(task='classification', time_budget=120, verbose=0, estimator_list=['lgbm', 'rf'])
model.fit(df_train.drop(target_variable, axis=1), df_train[target_variable])

df_test = df.drop(df_train.index)
y_pred = model.predict(df_test.drop(target_variable, axis=1))

f1score = f1_score(df_test[target_variable], y_pred, pos_label='yes')*100
print(f'performance of model is {f1score} %')

performance of model is 52.3524379811805 %

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت اول
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
همان‌طور که قبلا گفته شد، در ستون‌های دسته‌ای این دیتافریم، مقادیر گم‌شده وجود دارد. به عنوان قسمت اول از این سوال، از شما می‌خواهیم:
</font>
</p>
<ol dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
    <li>اسم همه ستون‌های دسته‌ای دیتافریم را درون لیستی به اسم <code>categorical_cols</code> بریزید. متغیر هدف نباید در این لیست قرار گرفته باشد.</li>
    <li>سپس به ازای همه ستون‌هایی که اسم‌شان در <code>categorical_cols</code> وجود دارد، مقادیر گم‌شده هر ستون را با پر تکرارترین مقدار آن ستون جایگزین کنید. دیتافریمی که هیچ مقدار گم‌شده‌ای ندارد را درون خود دیتافریم <code>df</code> ذخیره کنید. بنابراین بعد از حل قسمت اول، دیتافریم <code>df</code> هیچ مقدار گم‌شده‌ای نباید داشته باشد.</li>
</ol>

In [ ]:
# TO-DO: fill `categorical_cols` and fill na values in categorical columns of `df` dataframe.
categorical_cols = ['job', 'marital', 'education', 'default', 'housing', 'loan',
                    'is_telephone_contact', 'month', 'day_of_week', 'poutcome']

# جایگزینی مقادیر گم‌شده با پر تکرارترین مقدار هر ستون
for col in categorical_cols:
    most_frequent = df[col].mode()[0]  # پیدا کردن پر تکرارترین مقدار ستون
    df[col].fillna(most_frequent, inplace=True)

df

/tmp/ipython-input-3-823584825.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(most_frequent, inplace=True)

,age,job,marital,education,default,housing,loan,is_telephone_contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,y
0,56,housemaid,married,basic.4y,no,no,no,yes,may,mon,261,1,999,0,nonexistent,no
1,57,services,married,high.school,no,no,no,yes,may,mon,149,1,999,0,nonexistent,no
2,37,services,married,high.school,no,yes,no,yes,may,mon,226,1,999,0,nonexistent,no
3,40,admin.,married,basic.6y,no,no,no,yes,may,mon,151,1,999,0,nonexistent,no
4,56,services,married,high.school,no,no,yes,yes,may,mon,307,1,999,0,nonexistent,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,no,nov,fri,334,1,999,0,nonexistent,yes
41184,46,blue-collar,married,professional.course,no,no,no,no,nov,fri,383,1,999,0,nonexistent,no
41185,56,retired,married,university.degree,no,yes,no,no,nov,fri,189,2,999,0,nonexistent,no
41186,44,technician,married,professional.course,no,no,no,no,nov,fri,442,1,999,0,nonexistent,yes
41187,74,retired,married,professional.course,no,yes,no,no,nov,fri,239,3,999,1,failure,no

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت دوم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در این قسمت از شما انتظار داریم ۴ لیست آماده کنید. در هر لیست، ستون‌های دیتافریم <code>df</code> به تفکیک نوع‌شان طبقه‌بندی شده‌اند.

<ul dir=rtl>
    <li>در لیست <code>continuous_cols</code> اسامی ستون‌هایی را بنویسید که مقدار پیوسته دارند.</li>
    <li>در لیست <code>binary_cols</code> اسامی ستون‌هایی را بنویسید که مقدار گسسته دودویی دارند.</li>
    <li>در لیست <code>nominal_cols</code> اسامی ستون‌هایی را بنویسید که مقدار اسمی دارند.</li>
    <li>در لیست <code>ordinal_cols</code> اسامی ستون‌هایی را بنویسید که مقدار ترتیبی دارند.</li>
</ul>
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
توجه کنید که نوع (<code>dtype</code>) تمام متغیر‌هایی که در بالا معرفی شدند، باید حتما لیست باشد.
</font>
</p>

In [ ]:
# لیست‌های طبقه‌بندی‌شده بر اساس نوع ستون‌ها
continuous_cols = ['age', 'duration', 'campaign', 'pdays', 'previous']

# ستون‌های دودویی: فقط yes/no (شامل y نیست)
binary_cols = ['default', 'housing', 'loan', 'is_telephone_contact']

# ستون‌های ترتیبی
ordinal_cols = ['education', 'month', 'poutcome','day_of_week']

# ستون‌های اسمی: ستون‌های categorical که ترتیبی نیستند و بیشتر از 2 مقدار دارند
nominal_cols = ['job', 'marital']

# بررسی صحت لیست‌ها
print("Continuous columns:", continuous_cols)
print("Binary columns:", binary_cols)
print("Nominal columns:", nominal_cols)
print("Ordinal columns:", ordinal_cols)
df

Continuous columns: ['age', 'duration', 'campaign', 'pdays', 'previous']
Binary columns: ['default', 'housing', 'loan', 'is_telephone_contact']
Nominal columns: ['job', 'marital']
Ordinal columns: ['education', 'month', 'poutcome', 'day_of_week']

,age,job,marital,education,default,housing,loan,is_telephone_contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,y
0,56,housemaid,married,basic.4y,no,no,no,yes,may,mon,261,1,999,0,nonexistent,no
1,57,services,married,high.school,no,no,no,yes,may,mon,149,1,999,0,nonexistent,no
2,37,services,married,high.school,no,yes,no,yes,may,mon,226,1,999,0,nonexistent,no
3,40,admin.,married,basic.6y,no,no,no,yes,may,mon,151,1,999,0,nonexistent,no
4,56,services,married,high.school,no,no,yes,yes,may,mon,307,1,999,0,nonexistent,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,no,nov,fri,334,1,999,0,nonexistent,yes
41184,46,blue-collar,married,professional.course,no,no,no,no,nov,fri,383,1,999,0,nonexistent,no
41185,56,retired,married,university.degree,no,yes,no,no,nov,fri,189,2,999,0,nonexistent,no
41186,44,technician,married,professional.course,no,no,no,no,nov,fri,442,1,999,0,nonexistent,yes
41187,74,retired,married,professional.course,no,yes,no,no,nov,fri,239,3,999,1,failure,no

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت سوم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در قسمت سوم از شما می‌خواهیم دیتافریمی داشته باشید که فقط شامل ستون‌های دودویی دیتافریم <code>df</code> باشد. سپس همه مقادیر دیتافریم جدید را به عدد تبدیل کنید.
<br>
با استفاده از <code>binary_cols</code> می‌توانید دیتافریم <code>binary_df</code>  را بسازید.
در حقیقت دیتافریم <code>binary_df</code> بخشی از دیتافریم <code>df</code> است که فقط شامل ستون‌های دودویی آن باشد. یعنی هیچ ستون دیگری با مقادیر پیوسته، اسمی یا ترتیبی درون دیتافریم <code>binary_df</code> وجود ندارد. توجه کنید که تمام مقادیر این دیتافریم باید عدد باشند (به‌جای <code>yes</code> عدد <code>1</code> و به جای <code>no</code> عدد <code>0</code> قرار دهید).
</font>
</p>

In [ ]:
# TO-DO: create `binary_df` and replace all `object` values with numeric ones
binary_df = df[binary_cols].copy()

# 2. تبدیل مقادیر yes به 1 و no به 0
binary_df = binary_df.replace({'yes': 1, 'no': 0})

# نمایش برای اطمینان
print(binary_df.head())
df

   default  housing  loan  is_telephone_contact
0        0        0     0                     1
1        0        0     0                     1
2        0        1     0                     1
3        0        0     0                     1
4        0        0     1                     1

/tmp/ipython-input-5-3456852714.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  binary_df = binary_df.replace({'yes': 1, 'no': 0})

,age,job,marital,education,default,housing,loan,is_telephone_contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,y
0,56,housemaid,married,basic.4y,no,no,no,yes,may,mon,261,1,999,0,nonexistent,no
1,57,services,married,high.school,no,no,no,yes,may,mon,149,1,999,0,nonexistent,no
2,37,services,married,high.school,no,yes,no,yes,may,mon,226,1,999,0,nonexistent,no
3,40,admin.,married,basic.6y,no,no,no,yes,may,mon,151,1,999,0,nonexistent,no
4,56,services,married,high.school,no,no,yes,yes,may,mon,307,1,999,0,nonexistent,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,no,nov,fri,334,1,999,0,nonexistent,yes
41184,46,blue-collar,married,professional.course,no,no,no,no,nov,fri,383,1,999,0,nonexistent,no
41185,56,retired,married,university.degree,no,yes,no,no,nov,fri,189,2,999,0,nonexistent,no
41186,44,technician,married,professional.course,no,no,no,no,nov,fri,442,1,999,0,nonexistent,yes
41187,74,retired,married,professional.course,no,yes,no,no,nov,fri,239,3,999,1,failure,no

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت چهارم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در قسمت چهارم از شما می‌خواهیم دیتافریمی داشته باشید که فقط شامل ستون‌های اسمی دیتافریم <code>df</code> باشد.
<br>
با استفاده از <code>nominal_cols</code> دیتافریم <code>nominal_df</code>   را بسازید.
چون در ویژگی‌های اسمی، هیچ ترتیبی وجود ندارد، باید به شکل One-Hot درآیند.
نحوه‌ی کدگذاری One-Hot ستون‌های گسسته اسمی، باید به شکلی باشد که اسم ستون‌هایی که تشکیل می‌شوند، دارای دو بخش باشد. در بخش اول، <b>اسم ستونی</b> که کدگذاری می‌شود و در بخش دوم اسم <b>مقدار اسمی</b> بیاید، در حالی که این دو بخش با علامت «زیرخط» (<code>_</code>) از هم جدا شده باشند.
برای درک بهتر، به مثال زیر توجه کنید.
فرض کنید ستون خیالی به اسم <code>imaginary_col</code> درون مجموعه‌داده وجود می‌داشت که دارای مقادیری از نوع اسمی به شکل زیر بود :
</font>
</p>

<center>
<div style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
        
|<code>imaginary_col</code> |
| :---: |
|<code>val1</code>|
|<code>val1</code>|
|<code>val2</code>|
|<code>val3</code>|
|<code>val2</code>|
|<code>val1</code>|
|<code>val3</code>|

</font>
</div>
</center>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    چیزی که شما باید در نهایت  برای این ستون آماده کنید به شکل زیر خواهد بود:
</font>
</p>

<center>
<div style="line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
        
|<code>imaginary_col_val1</code>|<code>imaginary_col_val2</code>|<code>imaginary_col_val3</code>|
| :---: | :---: | :---: |
|<code>1</code>|<code>0</code>|<code>0</code>|
|<code>1</code>|<code>0</code>|<code>0</code>|
|<code>0</code>|<code>1</code>|<code>0</code>|
|<code>0</code>|<code>0</code>|<code>1</code>|
|<code>0</code>|<code>1</code>|<code>0</code>|
|<code>1</code>|<code>0</code>|<code>0</code>|
|<code>0</code>|<code>0</code>|<code>1</code>|

</font>
</div>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
به ازای هر ستونی از دیتافریم <code>df</code>  که از نوع اسمی است، این کار رو تکرار کنید.
در نهایت جدول ایجاد شده ناشی از One-Hot کردن هر ستون را به یکدیگر متصل کنید و نتیجه نهایی را درون متغیر <code>nominal_df</code> بریزید.
توجه داشته باشید که دیتافریم <code>nominal_df</code> به هیچ وجه نباید شامل خود ستون‌هایی باشد که One-Hot شدند. صرفاً درون این دیتافریم، کد شده‌ی ستون‌ها را قرار دهید.
</font>
</p>

In [ ]:
# TO-DO: create `nominal_df` according to above explanations
# گرفتن فقط ستون‌های اسمی از دیتافریم
# حذف ستون هدف از df (اگر خواستی)
nominal_data = df[nominal_cols].copy()

# استفاده از get_dummies با prefix برای تست موفق
nominal_df = pd.get_dummies(nominal_data, prefix=nominal_cols, prefix_sep='_')


nominal_df.head()

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,marital_divorced,marital_married,marital_single
0,False,False,False,True,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,True,False,False,False,False,True,False
2,False,False,False,False,False,False,False,True,False,False,False,False,True,False
3,True,False,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,True,False,False,False,False,True,False

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت پنجم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در قسمت پنجم از شما می‌خواهیم دیتافریمی داشته باشید که فقط شامل ستون‌های ترتیبی دیتافریم <code>df</code> باشد. سپس همه مقادیر دیتافریم جدید را به عدد تبدیل کنید.
<br>
با استفاده از <code>ordinal_cols</code> دیتافریم <code>ordinal_df</code>   را بسازید.
همانند کاری که در قسمت سوم برای ستون‌های دودویی کردید، این بار برای ستون‌های ترتیبی هم انجام دهید. یعنی با استفاده از جدول تبدیلات که در ابتدای تمرین آورده شد، مقادیر موجود در دیتافریم <code>ordinal_df</code> را به عدد تبدیل کنید.
</font>
</p>

In [ ]:
ordinal_cols = ['education', 'month', 'poutcome', 'day_of_week']
ordinal_df = df[ordinal_cols].copy()

# نگاشت‌ها
edu_map = {
    'illiterate': 0,
    'basic.4y': 1,
    'basic.6y': 2,
    'basic.9y': 3,
    'high.school': 4,
    'professional.course': 5,
    'university.degree': 6
}

month_map = {
    'jan': 0, 'feb': 1, 'mar': 2, 'apr': 3, 'may': 4, 'jun': 5,
    'jul': 6, 'aug': 7, 'sep': 8, 'oct': 9, 'nov': 10, 'dec': 11
}

pout_map = {'failure': -1, 'nonexistent': 0, 'success': 1}

day_map = {'mon': 0, 'tue': 1, 'wed': 2, 'thu': 3, 'fri': 4, 'sat': 5, 'sun': 6}



# اعمال نگاشت‌ها
ordinal_df['education'] = ordinal_df['education'].map(edu_map)
ordinal_df['month'] = ordinal_df['month'].map(month_map)
ordinal_df['poutcome'] = ordinal_df['poutcome'].map(pout_map)
ordinal_df['day_of_week'] = ordinal_df['day_of_week'].map(day_map)

# نمایش
ordinal_df.head()

   education  month  poutcome  day_of_week
0          1      4         0            0
1          4      4         0            0
2          4      4         0            0
3          2      4         0            0
4          4      4         0            0

In [ ]:
import pandas as pd

df = pd.read_csv('df.csv')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zipfile
import joblib
from google.colab import files  # ← اضافه شده برای دانلود فایل

# --- ذخیره لیست‌ها ---
joblib.dump(categorical_cols, "categorical_cols")
joblib.dump(continuous_cols, "continuous_cols")
joblib.dump(binary_cols, "binary_cols")
joblib.dump(nominal_cols, "nominal_cols")
joblib.dump(ordinal_cols, "ordinal_cols")

# --- ذخیره دیتافریم‌ها ---
binary_df.to_csv('binary_df.csv', index=False)
nominal_df.to_csv('nominal_df.csv', index=False)
ordinal_df.to_csv('ordinal_df.csv', index=False)
df.to_csv('df.csv', index=False)

# --- فشرده‌سازی فایل‌ها ---
def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write(file_name, compress_type=compression)

# حذف فایل نوت‌بوک از لیست (در Colab در دسترس نیست)
file_names = [
    "categorical_cols",
    "continuous_cols",
    "binary_cols",
    "nominal_cols",
    "ordinal_cols",
    "binary_df.csv",
    "nominal_df.csv",
    "ordinal_df.csv",
    "df.csv"
]

# اجرای فشرده‌سازی
compress(file_names)

# --- دانلود فایل فشرده ---
files.download("result.zip")

File Paths:
['categorical_cols', 'continuous_cols', 'binary_cols', 'nominal_cols', 'ordinal_cols', 'binary_df.csv', 'nominal_df.csv', 'ordinal_df.csv', 'df.csv']

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    حال که سوالات را حل کردید، پیشنهاد می‌کنیم مجدداً روی مجموعه‌داده جدیدی که به دست آوردید، مدل‌سازی کنید تا تاثیر پیش‌پردازش را در نتیجه نهایی مشاهده کنید.
    برای انجام مدل‌سازی دوباره، کافیست سلول زیر را اجرا کنید.
    اگر اجرای این سلول با شکست مواجه شد، می‌تواند به یکی از دلایل زیر باشد.
    <ul dir=rtl>
        <li>
            کتابخانه‌ی Fast Auto ML را نصب نکرده باشید.
        </li>
        <li>
           پیش‌پردازش‌های توضیح داده‌شده را اشتباه انجام داده باشید.
        </li>
    </ul>
</font>
</p>

In [ ]:
target_variable = 'y'
new_df = df[continuous_cols].join([binary_df, nominal_df, ordinal_df])

model = AutoML(task='classification', time_budget=120, verbose=0, estimator_list=['lgbm', 'rf'])
model.fit(new_df, df[target_variable])

df_test = new_df.join(df.y).sample(frac=0.3, random_state=313)
y_pred = model.predict(df_test.drop(target_variable, axis=1))

f1score = f1_score(df_test[target_variable], y_pred, pos_label='yes')*100
print(f'performance of model is {f1score} %')

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
می‌توانید تلاش کنید تا با انجام پیش‌پردازش‌های بیشتر، عملکرد مدل را بیشتر هم تقویت کنید!    
</font>
</p>