<a href="https://colab.research.google.com/github/Taheri1400/machine-learning-projects/blob/main/tsubasa_solved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
سوباسا
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مقدمه
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    تحلیل داده‌های فوتبال، یکی از کارهای مرسومی است که تیم‌های مطرح برای کسب نتایج بهتر انجام می‌دهند. به منظور جمع‌آوری داده، نرم‌افزارهایی وجود دارند که بازی‌های فوتبال را مورد تحلیل و آنالیز قرار می‌دهند و خلاصه آن را در قالب دشبوردهای مختلف ارائه می‌کنند. این نرم‌افزارها می‌توانند ضربات به چهارچوب و سایر اتفاقات بازی را رصد کنند. داده این تمرین نیز، خروجی یکی از همین نرم‌افزارهاست که مشغول تحلیل مسابقات تیم شاهین (تیم کاپیتان سوباسا) بوده است.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
مجموعه داده تمرین دارای ۸۹۲۵ سطر و ۱۲ ستون است که در جدول زیر، توضیحات هر ستون آورده شده است.
    <br>    
    البته داده اصلی مسابقات تیم شاهین، بیشتر از مجموعه داده‌ای است که در این تمرین به شما داده‌ایم. زیرا سرمربی تیم شاهین از ما خواسته که فقط شوت‌های به سمت چارچوب تیم را تحلیل کنیم. بنابراین داده این سوال، در هر سطر اطلاعات یکی از شوت‌های سمت چارچوب را به‌دست می‌دهد.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<table dir=rtl align = center>
    
<tr>
    <th align = center><font face="vazirmatn" size=3>نام ستون</font></th>
    <th align = center><font face="vazirmatn" size=3>توضیح</font></th>
</tr>

<tr>
    <td align = center><font face="vazirmatn" size=3>matchId</font></td>
    <td align = center><font face="vazirmatn" size=3>شناسه بازی</font></td>
</tr>
    
<tr>
    <td align = center><font face="vazirmatn" size=3>playerId</font></td>
    <td align = center><font face="vazirmatn" size=3>شناسه بازیکن</font></td>
</tr>
    
<tr>
    <td align = center><font face="vazirmatn" size=3>playType</font></td>
    <td align = center><font face="vazirmatn" size=3>موقعیت بازی که در آن ضربه زده شد (جریان‌ بازی، پنالتی، ضربه‌ آزاد ‌مستقیم، مستقیم ‌از ‌کرنر)</font></td>
</tr>
    
<tr>
    <td align = center><font face="vazirmatn" size=3>bodyPart</font></td>
    <td align = center><font face="vazirmatn" size=3>بخشی از بدن که با آن شوت زده شده‌است (پای چپ، پای راست، سَر، سایر)</font></td>
</tr>
    
<tr>
    <td align = center><font face="vazirmatn" size=3>x</font></td>
    <td align = center><font face="vazirmatn" size=3>موقعیت شوت در زمین به متر (مختصات x)</font></td>
</tr>
    
<tr>
    <td align = center><font face="vazirmatn" size=3>y</font></td>
    <td align = center><font face="vazirmatn" size=3>موقعیت شوت در زمین به متر (مختصات y)</font></td>
</tr>
    
<tr>
    <td align = center><font face="vazirmatn" size=3>interveningOpponents</font></td>
    <td align = center><font face="vazirmatn" size=3>تعداد بازیکنان حریف که در لحظه شوت‌زدن مانع دید شوت‌زننده به دروازه شده بودند</font></td>
</tr>
    
<tr>
    <td align = center><font face="vazirmatn" size=3>interveningTeammates</font></td>
    <td align = center><font face="vazirmatn" size=3>تعداد هم‌تیمی‌هایی که در لحظه شوت زدن مانع دید شوت‌زننده به دروازه شده بودند</font></td>
</tr>
    
<tr>
    <td align = center><font face="vazirmatn" size=3>interferenceOnShooter</font></td>
    <td align = center><font face="vazirmatn" size=3>میزان دخالت مستقیم تیم مدافع بر روی شوت‌زننده (کم - هیچ بازیکن تیم حریف در یک متری شوت‌زننده نیست، متوسط - یک بازیکن حریف در ۱متری شوت‌زننده قرار دارد، زیاد - بیشتر از یک بازیکن حریف در ۱متری شوت‌زننده قرار دارند)</font></td>
</tr>
    
<tr>
    <td align = center><font face="vazirmatn" size=3>minute</font></td>
    <td align = center><font face="vazirmatn" size=3>دقیقه زدن شوت</font></td>
</tr>
    
<tr>
    <td align = center><font face="vazirmatn" size=3>second	</font></td>
    <td align = center><font face="vazirmatn" size=3>ثانیه زدن شوت</font></td>
</tr>
    
<tr>
    <td align = center><font face="vazirmatn" size=3>outcome</font></td>
    <td align = center><font face="vazirmatn" size=3>نتیجه شوت (برخورد به دفاع، موقعیت از دست رفته، برخورد به تیردروازه، مهار توسط دروازه‌بان، گُل، گُل به‌خودی)</font></td>
</tr>
    
</table>
</p>

---------

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
مبدا مختصات (۰,۰) مرکز دروازه‌ی تحت شوت می‌باشد و مختصات (x,y)، فاصله طولی (x) و عرضی (y) محل زدن شوت تا مبدا مختصات‌ را به متر تعیین می‌کند، به عنوان مثال، موقعیت پنالتی در مختصات (۱۱,۰) می‌باشد.
    <br>
برای آشنایی بیشتر با زمین فوتبال و ابعاد قسمت‌های مختلف آن، شما به عکس زیر از
    <a href="https://fa.wikipedia.org/wiki/%D8%B2%D9%85%DB%8C%D9%86_%D9%81%D9%88%D8%AA%D8%A8%D8%A7%D9%84" >ویکی‌پدیا فارسی</a> دسترسی دارید
</font>
</p>

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Football_pitch_metric.svg/800px-Football_pitch_metric.svg.png"></img>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
هدف مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در این تمرین قصد داریم به سرمربی تیم شاهین کمک کنیم که پیشبینی کند هر شوت، با چه احتمالی ممکن است به گل تبدیل شود.
    <br>
    چون هنوز با مدلسازی آشنا نیستیم، از فرد دیگری برای فرایند مدلسازی کمک گرفته‌ایم و خود صرفا در پیش‌پردازش داده کمک می‌دهیم و نتیجه پیش‌پردازش‌ها را در عملکرد نهایی مدل مشاهده خواهیم کرد.
    <br>
    پس از انجام پیش‌پردازش‌های ابتدایی مثل تمیز کردن برخی ستون‌ها و ساختن ویژگی‌های جدید، سراغ مهمترین هدف این تمرین یعنی <b>انتخاب ویژگی</b> می‌رویم.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید و سپس مجموعه داده را از فایل بخوانید و در متغیر df بریزید.
</font>
</p>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('train.csv')

Saving train.csv to train.csv

In [ ]:
df

,matchId,playerId,playType,bodyPart,x,y,interveningOpponents,interveningTeammates,interferenceOnShooter,minute,second,outcome
0,m_91,p_103,جریان بازی,پای راست,13.47,-11.22,1,0,متوسط,70,9,گُل
1,m_17,p_16,جریان بازی,پای چپ,9.48,14.22,3,0,متوسط,55,4,مهار توسط دروازه بان
2,m_111,p_88,ضربه آزاد مستقیم,پای چپ,29.43,-1.25,6,2,کم,86,31,مهار توسط دروازه بان
3,m_142,p_87,جریان بازی,پای راست,26.93,1.00,4,1,متوسط,77,2,موقعیت از دست رفته
4,m_117,p_9,جریان بازی,پای راست,10.72,5.24,2,0,متوسط,76,46,گُل
...,...,...,...,...,...,...,...,...,...,...,...,...
8920,m_57,p_115,جریان بازی,سر,6.48,3.99,3,0,زیاد,69,50,موقعیت از دست رفته
8921,m_59,p_76,جریان بازی,پای راست,21.45,-8.73,4,1,متوسط,15,53,برخورد به دفاع
8922,m_55,p_150,جریان بازی,پای چپ,11.97,3.24,3,0,متوسط,84,34,موقعیت از دست رفته
8923,m_33,p_130,جریان بازی,پای راست,6.48,-6.98,1,0,زیاد,4,39,موقعیت از دست رفته
8924,m_142,p_37,جریان بازی,پای راست,8.23,26.43,2,0,متوسط,72,17,مهار توسط دروازه بان

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت اول
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    به عنوان اولین قسمت از حل سوال، میخواهیم ستونی به اسم <code>label</code> به <code>df</code> اضافه کنیم.
    <br>
    در این سوال ما <b>گُل</b> و <b>گُل به خودی</b> را گل در نظر می‌گیریم. به عبارت بهتر، در پیشبینی احتمال گل، آن‌ها را معادل یکدیگر لحاظ می‌کنیم.
    <br>
    بنابراین ستون <code>label</code> به ازای سطرهایی که ستون <code>outcome</code>شان برابر گُل یا گُل به‌خودی است مقدار ۱ و در غیر این صورت مقدار ۰ خواهد داشت.
    <br>
    پس از محاسبه ستون <code>label</code> ستون <code>outcome</code> را برای همیشه از <code>df</code> حذف کنید.
</font>
</p>

In [ ]:


# ایجاد ستون label
df['label'] = df['outcome'].apply(lambda x: 1 if x in ['گُل', 'گُل به خودی'] else 0)

# حذف ستون outcome
df.drop('outcome', axis=1, inplace=True)

# نمایش چند سطر اول برای بررسی
df

,matchId,playerId,playType,bodyPart,x,y,interveningOpponents,interveningTeammates,interferenceOnShooter,minute,second,label
0,m_91,p_103,جریان بازی,پای راست,13.47,-11.22,1,0,متوسط,70,9,1
1,m_17,p_16,جریان بازی,پای چپ,9.48,14.22,3,0,متوسط,55,4,0
2,m_111,p_88,ضربه آزاد مستقیم,پای چپ,29.43,-1.25,6,2,کم,86,31,0
3,m_142,p_87,جریان بازی,پای راست,26.93,1.00,4,1,متوسط,77,2,0
4,m_117,p_9,جریان بازی,پای راست,10.72,5.24,2,0,متوسط,76,46,1
...,...,...,...,...,...,...,...,...,...,...,...,...
8920,m_57,p_115,جریان بازی,سر,6.48,3.99,3,0,زیاد,69,50,0
8921,m_59,p_76,جریان بازی,پای راست,21.45,-8.73,4,1,متوسط,15,53,0
8922,m_55,p_150,جریان بازی,پای چپ,11.97,3.24,3,0,متوسط,84,34,0
8923,m_33,p_130,جریان بازی,پای راست,6.48,-6.98,1,0,زیاد,4,39,0
8924,m_142,p_37,جریان بازی,پای راست,8.23,26.43,2,0,متوسط,72,17,0


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    برای آن که ارزش کار خود را درک کنید، نیاز است ابتدا که هیچگونه پیش‌پردازشی روی داده انجام نشده است، یکبار با آن مدلسازی کنید و عملکرد مدل را مشاهده کنید. با اجرای سلول زیر یک مدل روی داده آموزش می‌بیند و نتایجی تولید می‌کند.
    <br>
    اگر اجرای این سلول با شکست مواجه شد، می‌تواند به یکی از دلایل زیر باشد.
</font>
</p>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    <ul>
        <li>
            کتابخانه Fast Auto ML را نصب نکرده باشید.
        </li>
        <li>
            در بارگزاری مجموعه داده دچار مشکل شده باشید.
        </li>
    </ul>
</font>
</div>

In [ ]:
!pip install numpy==1.26.4

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.11/dist-packages (1.26.4)

In [ ]:
!pip install --upgrade flaml

Requirement already satisfied: flaml in /usr/local/lib/python3.11/dist-packages (2.3.5)
Requirement already satisfied: NumPy>=1.17 in /usr/local/lib/python3.11/dist-packages (from flaml) (1.26.4)

In [ ]:
from sklearn.model_selection import train_test_split
from flaml import AutoML
from sklearn.metrics import roc_auc_score

x_train,x_test , y_train,y_test = train_test_split(df.drop('label', axis=1), df.label, random_state=313, stratify=df.label)

model = AutoML(task='classification', time_budget=60, verbose=0)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print(f'performance of model is {roc_auc_score(y_test, y_pred)}')

INFO:flaml.tune.searcher.blendsearch:No low-cost partial config given to the search algorithm. For cost-frugal search, consider providing low-cost values for cost-related hps via 'low_cost_partial_config'. More info can be found at https://microsoft.github.io/FLAML/docs/FAQ#about-low_cost_partial_config-in-tune

performance of model is 0.5851342167855929

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت دوم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    یکی از اصول مهم در پیشبینی گل، آن است که مدل نهایی فارغ از آن که شوت در چه بازی و توسط چه بازیکنی انجام شده است، نتیجه را پیشبینی کند.
    <br>
    بنابراین در ابتدای کار، ستون‌های <code>matchId</code> و <code>playerId</code> را برای همیشه از <code>df</code> حذف کنید.
</font>
</p>

In [ ]:
#TODO: delete playerId and matchId columns from df
# حذف ستون‌های matchId و playerId
df.drop(['matchId', 'playerId'], axis=1, inplace=True)

# نمایش 5 سطر اول برای بررسی

df

,playType,bodyPart,x,y,interveningOpponents,interveningTeammates,interferenceOnShooter,minute,second,label
0,جریان بازی,پای راست,13.47,-11.22,1,0,متوسط,70,9,1
1,جریان بازی,پای چپ,9.48,14.22,3,0,متوسط,55,4,0
2,ضربه آزاد مستقیم,پای چپ,29.43,-1.25,6,2,کم,86,31,0
3,جریان بازی,پای راست,26.93,1.00,4,1,متوسط,77,2,0
4,جریان بازی,پای راست,10.72,5.24,2,0,متوسط,76,46,1
...,...,...,...,...,...,...,...,...,...,...
8920,جریان بازی,سر,6.48,3.99,3,0,زیاد,69,50,0
8921,جریان بازی,پای راست,21.45,-8.73,4,1,متوسط,15,53,0
8922,جریان بازی,پای چپ,11.97,3.24,3,0,متوسط,84,34,0
8923,جریان بازی,پای راست,6.48,-6.98,1,0,زیاد,4,39,0
8924,جریان بازی,پای راست,8.23,26.43,2,0,متوسط,72,17,0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت سوم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>  
به عنوان گام سوم، قصد داریم پای راست و چپ را معادل یکدیگر در نظر بگیریم.
    <br>
    بنابراین در قسمت سوم، مقادیر <b>پای راست</b> و <b>پای چپ</b> در ستون <code>bodyPart</code> را با کلمه <b>پا</b> جایگزین کنید.
</font>
</p>

In [ ]:
#TODO: replace `پای چپ` and `پای راست` with `پا`
df['bodyPart'] = df['bodyPart'].replace(['پای راست', 'پای چپ'], 'پا')
df

,playType,bodyPart,x,y,interveningOpponents,interveningTeammates,interferenceOnShooter,minute,second,label
0,جریان بازی,پا,13.47,-11.22,1,0,متوسط,70,9,1
1,جریان بازی,پا,9.48,14.22,3,0,متوسط,55,4,0
2,ضربه آزاد مستقیم,پا,29.43,-1.25,6,2,کم,86,31,0
3,جریان بازی,پا,26.93,1.00,4,1,متوسط,77,2,0
4,جریان بازی,پا,10.72,5.24,2,0,متوسط,76,46,1
...,...,...,...,...,...,...,...,...,...,...
8920,جریان بازی,سر,6.48,3.99,3,0,زیاد,69,50,0
8921,جریان بازی,پا,21.45,-8.73,4,1,متوسط,15,53,0
8922,جریان بازی,پا,11.97,3.24,3,0,متوسط,84,34,0
8923,جریان بازی,پا,6.48,-6.98,1,0,زیاد,4,39,0
8924,جریان بازی,پا,8.23,26.43,2,0,متوسط,72,17,0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت چهارم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در قسمت چهارم قصد داریم، فاصله مبدا شوت و زاویه آن را به عنوان دو ستون جدید با نام‌های <code>distance</code> و <code>angle</code> به مجموعه داده اضافه کنیم.
    <br>
    در ادامه فرمول‌هایی که طبق آن‌ها می‌توانیم فاصله و زاویه را محاسبه کنیم، آورده شده است.
    <br>
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: center;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

<br>

$$distance = \sqrt{x^2 + y^2}$$

<br>
    
$$ angle=  \left\{
\begin{array}{}
      rad2deg(arctan(\theta)) & arctan(\theta) \geq 0  \\
      rad2deg(arctan(\theta) + \pi) & arctan(\theta) \lt 0 \\
\end{array}
\right. , \theta = \frac{7.32 * x}{x^2 + y^2 - (7.32 /2)^2} $$

</font>
</p>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    از دو فرمول بالا می‌توانیم نتیجه بگیریم، ستون <code>distance</code> باید از جنس float باشد.
    <br>
    همچنین متوجه می‌شویم که اعداد ستون <code>angle</code> که از جنس float هستند، بر حسب <b>درجه</b> حساب شده اند.
    <br>
    برای محاسبه عدد پی از np.pi استفاده کنید.
    <br>
    پس از محاسبه <code>distance</code> و <code>angle</code> لازم است دو ستون <code>x</code> و <code>y</code> را برای همیشه از دیتافریم حذف کنید.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    به عنوان تمرین اضافه، تلاش کنید درستی فرمولی که برای محاسبه زاویه ارائه شد را اثبات کنید.
    <br>
    راهنمایی : ۷.۳۲، طول دروازه است!
    <br>
    اثبات این فرمول، هیچ تاثیری در امتیاز کسب شده توسط شما برای این سوال نخواهد داشت و صرفا برای تمرین بیشتر شما طرح شده است.
</font>
</p>

In [ ]:
#TODO: add distance and angle column to df
import numpy as np

# تعریف ثابت‌ها
GOAL_WIDTH = 7.32
HALF_GOAL_WIDTH = GOAL_WIDTH / 2

# محاسبه فاصله
df['distance'] = np.sqrt(df['x']**2 + df['y']**2)

# محاسبه مقدار θ
numerator = GOAL_WIDTH * df['x']
denominator = df['x']**2 + df['y']**2 - (HALF_GOAL_WIDTH)**2

# جلوگیری از تقسیم بر صفر با جایگزینی مقادیر صفر با یک عدد بسیار کوچک
denominator = np.where(denominator == 0, 1e-9, denominator)
theta = numerator / denominator

# محاسبه زاویه بر اساس فرمول ارائه شده
arctan_vals = np.arctan(theta)
df['angle'] = np.degrees(
    np.where(arctan_vals >= 0,
             arctan_vals,
             arctan_vals + np.pi)
)



# نمایش 5 سطر اول برای بررسی
df

,playType,bodyPart,x,y,interveningOpponents,interveningTeammates,interferenceOnShooter,minute,second,label,distance,angle
0,جریان بازی,پا,13.47,-11.22,1,0,متوسط,70,9,1,17.530810,18.544088
1,جریان بازی,پا,9.48,14.22,3,0,متوسط,55,4,0,17.090313,13.982592
2,ضربه آزاد مستقیم,پا,29.43,-1.25,6,2,کم,86,31,0,29.456534,14.153255
3,جریان بازی,پا,26.93,1.00,4,1,متوسط,77,2,0,26.948560,15.458384
4,جریان بازی,پا,10.72,5.24,2,0,متوسط,76,46,1,11.932141,31.315918
...,...,...,...,...,...,...,...,...,...,...,...,...
8920,جریان بازی,سر,6.48,3.99,3,0,زیاد,69,50,0,7.609895,46.818116
8921,جریان بازی,پا,21.45,-8.73,4,1,متوسط,15,53,0,23.158484,16.713121
8922,جریان بازی,پا,11.97,3.24,3,0,متوسط,84,34,0,12.400746,31.970470
8923,جریان بازی,پا,6.48,-6.98,1,0,زیاد,4,39,0,9.524222,31.529506
8924,جریان بازی,پا,8.23,26.43,2,0,متوسط,72,17,0,27.681723,4.574906

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت پنجم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    با اجرای سلول زیر، متوجه خواهیم شد که در ستون <code>interferenceOnShooter</code> تعدادی مقدار گمشده وجود دارد که پیش از مدلسازی نهایی، لازم است آن را جبران کنیم.
    <br>
    همانطور که در توضیحات مجموعه داده گفته شد، ستون <code>interveningOpponents</code> نشان دهنده افرادی از تیم مقابل است که مانع دید شوت‌زننده بوده‌اند. از طرفی ستون <code>interferenceOnShooter</code> هم میزان اثرگذاری بازیکننان تیم مقابل را نشان می‌دهد. بنابراین ایده خوبی است که برای پر کردن مقادیر گمشده آن، از <code>interveningOpponents</code> استفاده کنیم.
    <br>
    بنابراین برای پرکردن مقادیر گمشده ستون <code>interferenceOnShooter</code>در هر سطر، اگر ستون <code>interveningOpponents</code> آن ۰ بود، عبارت <b>کم</b>، اگر برابر ۱ بود، عبارت <b>متوسط</b> و در غیر این صورت عبارت <b>زیاد</b> را جایگزین کنید.
</font>
</p>

In [ ]:
df.isna().sum()

playType                  0
bodyPart                  0
x                         0
y                         0
interveningOpponents      0
interveningTeammates      0
interferenceOnShooter    34
minute                    0
second                    0
label                     0
distance                  0
angle                     0
dtype: int64

In [ ]:
def map_interference(count):
    if count == 0:
        return 'کم'
    elif count == 1:
        return 'متوسط'
    else:  # count >= 2
        return 'زیاد'

# جایگزینی مقادیر گمشده بر اساس ستون interveningOpponents
mask = df['interferenceOnShooter'].isna()
df.loc[mask, 'interferenceOnShooter'] = df.loc[mask, 'interveningOpponents'].apply(map_interference)


df

,playType,bodyPart,x,y,interveningOpponents,interveningTeammates,interferenceOnShooter,minute,second,label,distance,angle
0,جریان بازی,پا,13.47,-11.22,1,0,متوسط,70,9,1,17.530810,18.544088
1,جریان بازی,پا,9.48,14.22,3,0,متوسط,55,4,0,17.090313,13.982592
2,ضربه آزاد مستقیم,پا,29.43,-1.25,6,2,کم,86,31,0,29.456534,14.153255
3,جریان بازی,پا,26.93,1.00,4,1,متوسط,77,2,0,26.948560,15.458384
4,جریان بازی,پا,10.72,5.24,2,0,متوسط,76,46,1,11.932141,31.315918
...,...,...,...,...,...,...,...,...,...,...,...,...
8920,جریان بازی,سر,6.48,3.99,3,0,زیاد,69,50,0,7.609895,46.818116
8921,جریان بازی,پا,21.45,-8.73,4,1,متوسط,15,53,0,23.158484,16.713121
8922,جریان بازی,پا,11.97,3.24,3,0,متوسط,84,34,0,12.400746,31.970470
8923,جریان بازی,پا,6.48,-6.98,1,0,زیاد,4,39,0,9.524222,31.529506
8924,جریان بازی,پا,8.23,26.43,2,0,متوسط,72,17,0,27.681723,4.574906

In [ ]:
print(df['interferenceOnShooter'].isna().sum())  # باید 0 چاپ کند
print(df['interferenceOnShooter'].unique())     # باید فقط ['کم', 'متوسط', 'زیاد'] نشان دهد

0
['متوسط' 'کم' 'زیاد']

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت ششم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در قسمت ششم وقت آن است که ستون‌هایی که مقادیر دسته‌ای دارند را کدگذار کنیم.
    <br>
    به این منظور، ستون‌های <code>playType</code> و <code>bodyPart</code> و <code>interferenceOnShooter</code> را به شکل <code>one-hot-encode</code> کدگذاری کنید.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    به عنوان مثال با استفاده از ستون <code>bodyPart</code> سه ستون با پیشوند <code>bodyPart</code> بسازید و آن‌ها را به دیتافریم <code>df</code> اضافه کنید.
    برای درک بهتر، تصور کنید این شش سطر زیر، بخشی از دیتافریم <code>df</code> باشند.
</font>
</p>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|bodyPart|
|-------|
|سر|
|پا|
|سر|
|سایر|
|پا|
|پا|
    
</font>
</div>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    انتظار داریم پس از انجام <code>one-hot-encode</code> سه ستون مانند جدول زیر به ازای این ۶ سطر به دیتافریم <code>df</code> اضافه شوند.
</font>
</p>



<div style="line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|bodyPartسرـ|bodyPartپاـ|bodyPartسایرـ|
|-------|-------|-------|
|1|0|0|
|0|1|0|
|1|0|0|
|0|0|1|
|0|1|0|
|0|1|0|
    
</font>
</div>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    با استفاده از ستون <code>playType</code> چهار ستون با پیشوند <code>playType</code> بسازید و آن‌ها را به دیتافریم <code>df</code> اضافه کنید.
    <br>
        با استفاده از ستون <code>interferenceOnShooter</code> سه ستون با پیشوند <code>interferenceOnShooter</code> بسازید و آن‌ها را به دیتافریم <code>df</code> اضافه کنید.
    <br>
    پس از اضافه شدن ۱۰ ستون به دیتافریم <code>df</code> که ناشی از <code>one-hot-encode</code> کردن سه ستون نام‌برده هستند، سه ستون <code>playType</code> و <code>bodyPart</code> و <code>interferenceOnShooter</code> را از دیتافریم <code>df</code> برای همیشه حذف کنید.
</font>
</p>

In [ ]:
df['playType'].value_counts()
print(df['playType'].isna().sum())

0

In [ ]:
df['bodyPart'].value_counts()
print(df['bodyPart'].isna().sum())

0

In [ ]:
df['interferenceOnShooter'].value_counts()
print(df['interferenceOnShooter'].isna().sum())

0

In [ ]:
# مرحله 1: One-hot encode برای bodyPart
body_part_dummies = pd.get_dummies(df['bodyPart'], prefix='bodyPart')

# مرحله 2: One-hot encode برای playType
play_type_dummies = pd.get_dummies(df['playType'], prefix='playType')

# مرحله 3: One-hot encode برای interferenceOnShooter
interference_dummies = pd.get_dummies(df['interferenceOnShooter'], prefix='interferenceOnShooter')

# مرحله 4: اضافه کردن همه‌ی ستون‌های جدید به دیتافریم اصلی
df = pd.concat([df, body_part_dummies, play_type_dummies, interference_dummies], axis=1)

# مرحله 5: حذف ستون‌های اصلی
df.drop(columns=['bodyPart', 'playType', 'interferenceOnShooter'], inplace=True)


df

,x,y,interveningOpponents,interveningTeammates,minute,second,label,distance,angle,bodyPart_سایر,bodyPart_سر,bodyPart_پا,playType_جریان بازی,playType_ضربه آزاد مستقیم,playType_مستقیم از کرنر,playType_پنالتی,interferenceOnShooter_زیاد,interferenceOnShooter_متوسط,interferenceOnShooter_کم
0,13.47,-11.22,1,0,70,9,1,17.530810,18.544088,False,False,True,True,False,False,False,False,True,False
1,9.48,14.22,3,0,55,4,0,17.090313,13.982592,False,False,True,True,False,False,False,False,True,False
2,29.43,-1.25,6,2,86,31,0,29.456534,14.153255,False,False,True,False,True,False,False,False,False,True
3,26.93,1.00,4,1,77,2,0,26.948560,15.458384,False,False,True,True,False,False,False,False,True,False
4,10.72,5.24,2,0,76,46,1,11.932141,31.315918,False,False,True,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8920,6.48,3.99,3,0,69,50,0,7.609895,46.818116,False,True,False,True,False,False,False,True,False,False
8921,21.45,-8.73,4,1,15,53,0,23.158484,16.713121,False,False,True,True,False,False,False,False,True,False
8922,11.97,3.24,3,0,84,34,0,12.400746,31.970470,False,False,True,True,False,False,False,False,True,False
8923,6.48,-6.98,1,0,4,39,0,9.524222,31.529506,False,False,True,True,False,False,False,True,False,False
8924,8.23,26.43,2,0,72,17,0,27.681723,4.574906,False,False,True,True,False,False,False,False,True,False

In [ ]:
df.head()            # بررسی سطرهای اول
df.shape             # تعداد ستون‌ها بعد از افزودن 10 ستون جدید
df.columns.tolist()  # لیست ستون‌ها برای اطمینان

['x',
 'y',
 'interveningOpponents',
 'interveningTeammates',
 'minute',
 'second',
 'label',
 'distance',
 'angle',
 'bodyPart_سایر',
 'bodyPart_سر',
 'bodyPart_پا',
 'playType_جریان بازی',
 'playType_ضربه آزاد مستقیم',
 'playType_مستقیم از کرنر',
 'playType_پنالتی',
 'interferenceOnShooter_زیاد',
 'interferenceOnShooter_متوسط',
 'interferenceOnShooter_کم']

In [ ]:
#TODO: encode `playType`, `bodyPart`, and `interferenceOnShooter` columns
# One-hot-encode سه ستون مشخص شده و اضافه کردن آن‌ها به df
#df = pd.get_dummies(df, columns=['playType', 'bodyPart', 'interferenceOnShooter'], drop_first=False)
#df

,interveningOpponents,interveningTeammates,minute,second,label,distance,angle,playType_جریان بازی,playType_ضربه آزاد مستقیم,playType_مستقیم از کرنر,playType_پنالتی,bodyPart_سایر,bodyPart_سر,bodyPart_پا,interferenceOnShooter_زیاد,interferenceOnShooter_متوسط,interferenceOnShooter_کم
0,1,0,70,9,1,17.530810,18.544088,True,False,False,False,False,False,True,False,True,False
1,3,0,55,4,0,17.090313,13.982592,True,False,False,False,False,False,True,False,True,False
2,6,2,86,31,0,29.456534,14.153255,False,True,False,False,False,False,True,False,False,True
3,4,1,77,2,0,26.948560,15.458384,True,False,False,False,False,False,True,False,True,False
4,2,0,76,46,1,11.932141,31.315918,True,False,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8920,3,0,69,50,0,7.609895,46.818116,True,False,False,False,False,True,False,True,False,False
8921,4,1,15,53,0,23.158484,16.713121,True,False,False,False,False,False,True,False,True,False
8922,3,0,84,34,0,12.400746,31.970470,True,False,False,False,False,False,True,False,True,False
8923,1,0,4,39,0,9.524222,31.529506,True,False,False,False,False,False,True,True,False,False
8924,2,0,72,17,0,27.681723,4.574906,True,False,False,False,False,False,True,False,True,False

In [ ]:
print(df.shape)
print(df.columns.tolist())

(8925, 19)
['x', 'y', 'interveningOpponents', 'interveningTeammates', 'minute', 'second', 'label', 'distance', 'angle', 'bodyPart_سایر', 'bodyPart_سر', 'bodyPart_پا', 'playType_جریان بازی', 'playType_ضربه آزاد مستقیم', 'playType_مستقیم از کرنر', 'playType_پنالتی', 'interferenceOnShooter_زیاد', 'interferenceOnShooter_متوسط', 'interferenceOnShooter_کم']

**bold text**<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت هفتم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    در قسمت پایانی تمرین «سوباسا» می‌خواهیم اهمیت ویژگی ها را محاسبه کنیم. به عبارت ساده‌تر میخواهیم بسنجیم هر ویژگی چقدر بر متغیر هدف مسئله (گل شدن یک شوت) تاثیرگذار است.
    <br>
    متغیر هدف مسئله، ستون <code>label</code> است.
    <br>
    برای رسیدن به این هدف از روش <code>mutual_info</code> استفاده خواهیم کرد. چون مسئله ما از جنس طبقه‌بندی (دسته‌بندی یا کلسیفیکیشن) است، از <code>mutual_info_classif</code> استفاده می‌کنیم. نحوه استفاده از این تابع را در ادامه مرور می‌کنیم!
    <br>
    گسسته یا پیوسته بودن یک ویژگی، در نحوه محاسبه اهمیت آن موثر است. پس فراموش نکنید هنگام محاسبه اهمیت، گسسته یا پیوسته بودن را لحاظ کنید.
    <br>
    همانطور که مطمئنا خودتان هم می‌دانید، تنها دو ستون <code>distance</code> و <code>angle</code> مقدار پیوسته دارند و بقیه ویژگی‌ها گسسته هستند.
    <br>
    یعنی حتی ستون‌های <code>minute</code> و <code>second</code> نیز مقدار <b>گسسته</b> دارند.
    <br>
    در تابع <code>mutual_info_classif</code> حتما مقدار آرگومان <code>random_state</code> را برابر ۱۴۰۱ قرار دهید. در غیر این صورت، پاسخ‌ ارسالی شما ممکن است متفاوت از مقداری باشد که سامانه داوری در نظر دارد.
    <br>
    وقتی مقدار اهمیت هر ویژگی را محاسبه کردید، وقت آن است که آن‌ها را در یک دیتافریم به اسم <code>feature_importance</code> ذخیره کنید.
    <br>
    این دیتافریم تنها یک ستون به اسم <code>fi</code> دارد که مقادیر آن، میزان اهمیت یک ویژگی است. نمایه‌های دیتافریم <code>feature_importance</code> در واقع اسم ستون‌ها هستند. پس این دیتافریم ۱۶ سطر و تنها ۱ ستون خواهد داشت.
    <br>
    پس از آن که سطرهای دیتافریم را مقداردهی کردید، آن را بر اساس ستون <code>fi</code> به صورت نزولی مرتب کنید.
</font>
</p>

<h3 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    استفاده از <code>scikit-learn</code>
</font>
</h3>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    روش انتخاب ویژگی «اطلاعات متقابل» برای مسايل دسته‌بندی، تحت عنوان <code>mutual_info_classif</code> در پکیج <code>feature_selection</code> این کتابخانه موجود است.
    <br>
    برخی از آرگومان‌های مهم آن در جدول زیر آمده است، اما جهت مطالعه‌ی کامل‌تر مستندات می‌توانید به <a href="https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.mutual_info_classif.html" target="_blank">این لینک</a> مراجعه فرمایید.
</font>
</p>

<center>
<div dir=rtl style="line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|آرگومان|توضیحات|
|:------:|:---:|
|<code>X</code>|مجموعه ویژگی‌ها بدون در نظر گرفتن متغیر هدف|
|<code>y</code>|متغیر هدف|
|<code>discrete_features</code>|یک لیست که می‌تواند دو حالت داشته باشد:<ul><li>یک آرایه بولینی به طول تعداد ستون‌های X که المان i ام آن بیانگر آن است که آیا ستون i ام X متغیر گسسته است یا خیر!</li><li>یک لیست از اندیس ستون‌هایی که مقدار گسسته دارند!</li></ul>|
|<code>random_state</code>|عددی برای مقداردهی اولیه موتور تولید اعداد رندوم. عدد رندوم به منظور عدم تکرار مقادیر پیوسته، به آن‌ها افزوده می‌شود|
    
</font>
</div>
</center>

In [ ]:
from sklearn.feature_selection import mutual_info_classif



# 1. تعریف X و y
X = df.drop(columns=['label'])
y = df['label']

# 2. مشخص کردن اینکه کدام ستون گسسته است:
# فقط دو ویژگی پیوسته هستند: distance و angle → بقیه گسسته‌اند
# discrete_features به صورت boolean list
discrete_mask = [col not in ['distance', 'angle'] for col in X.columns]

# 3. محاسبه میزان اهمیت ویژگی‌ها با mutual_info_classif
mi = mutual_info_classif(X, y, discrete_features=discrete_mask, random_state=1401)

# 4. ساخت دیتافریم نهایی
feature_importance = pd.DataFrame({'fi': mi}, index=X.columns)

# 5. مرتب‌سازی به صورت نزولی
feature_importance.sort_values(by='fi', ascending=False, inplace=True)

# نمایش خروجی نهایی
feature_importance

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/cluster/_supervised.py:59: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/cluster/_supervised.py:59: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)

                                       fi
angle                        5.955956e-02
distance                     5.800996e-02
x                            4.759569e-02
interveningOpponents         4.429951e-02
y                            4.001684e-02
playType_پنالتی              1.581679e-02
interveningTeammates         8.254063e-03
minute                       5.363962e-03
interferenceOnShooter_کم     4.307430e-03
second                       3.790938e-03
playType_جریان بازی          3.353142e-03
interferenceOnShooter_زیاد   3.124208e-03
bodyPart_سایر                1.326695e-03
interferenceOnShooter_متوسط  6.990951e-04
playType_ضربه آزاد مستقیم    5.282856e-04
playType_مستقیم از کرنر      1.854871e-04
bodyPart_پا                  6.951808e-05
bodyPart_سر                  6.569820e-07

In [ ]:
df

,x,y,interveningOpponents,interveningTeammates,minute,second,label,distance,angle,bodyPart_سایر,bodyPart_سر,bodyPart_پا,playType_جریان بازی,playType_ضربه آزاد مستقیم,playType_مستقیم از کرنر,playType_پنالتی,interferenceOnShooter_زیاد,interferenceOnShooter_متوسط,interferenceOnShooter_کم
0,13.47,-11.22,1,0,70,9,1,17.530810,18.544088,False,False,True,True,False,False,False,False,True,False
1,9.48,14.22,3,0,55,4,0,17.090313,13.982592,False,False,True,True,False,False,False,False,True,False
2,29.43,-1.25,6,2,86,31,0,29.456534,14.153255,False,False,True,False,True,False,False,False,False,True
3,26.93,1.00,4,1,77,2,0,26.948560,15.458384,False,False,True,True,False,False,False,False,True,False
4,10.72,5.24,2,0,76,46,1,11.932141,31.315918,False,False,True,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8920,6.48,3.99,3,0,69,50,0,7.609895,46.818116,False,True,False,True,False,False,False,True,False,False
8921,21.45,-8.73,4,1,15,53,0,23.158484,16.713121,False,False,True,True,False,False,False,False,True,False
8922,11.97,3.24,3,0,84,34,0,12.400746,31.970470,False,False,True,True,False,False,False,False,True,False
8923,6.48,-6.98,1,0,4,39,0,9.524222,31.529506,False,False,True,True,False,False,False,True,False,False
8924,8.23,26.43,2,0,72,17,0,27.681723,4.574906,False,False,True,True,False,False,False,False,True,False

In [ ]:
print(df.shape)
print(df.columns.tolist())

(8925, 19)
['x', 'y', 'interveningOpponents', 'interveningTeammates', 'minute', 'second', 'label', 'distance', 'angle', 'bodyPart_سایر', 'bodyPart_سر', 'bodyPart_پا', 'playType_جریان بازی', 'playType_ضربه آزاد مستقیم', 'playType_مستقیم از کرنر', 'playType_پنالتی', 'interferenceOnShooter_زیاد', 'interferenceOnShooter_متوسط', 'interferenceOnShooter_کم']

In [ ]:
print("تعداد ستون‌های df:", df.shape[1])  # باید 19 باشد
print("تعداد سطرهای feature_importance:", feature_importance.shape[0])  # باید 18 باشد

تعداد ستون‌های df: 19
تعداد سطرهای feature_importance: 18

In [ ]:
import pandas as pd

df = pd.read_csv('df.csv')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

In [ ]:
import zipfile
import joblib

feature_importance.to_csv('feature_importance.csv',index=True)
df.to_csv('df.csv', index=False)

def compress(file_names):
    print("File Paths:")
    print(file_names)
    # Select the compression mode ZIP_DEFLATED for compression
    # or zipfile.ZIP_STORED to just store the file
    compression = zipfile.ZIP_DEFLATED
    # create the zip file first parameter path/name, second mode
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            # Add file to the zip file
            # first parameter file to zip, second filename in zip
            zf.write('./' + file_name, file_name, compress_type=compression)


file_names = ['df.csv','feature_importance.csv', 'tsubasa.ipynb']
compress(file_names)
# اجرای فشرده‌سازی
compress(file_names)

# --- دانلود فایل فشرده ---
files.download("result.zip")

File Paths:
['df.csv', 'feature_importance.csv', 'tsubasa.ipynb']
File Paths:
['df.csv', 'feature_importance.csv', 'tsubasa.ipynb']


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    پس از اجرای سلول بالا، می‌توانید برای کسب نمره، فایل results.zip را برای سامانه داوری ارسال کنید.
    <br>
    اگر تمایل به مشاهده تاثیر پیش‌پردازش‌های انجام‌شده دارید، سلول‌های زیر را اجرا کنید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مدلسازی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    حال که سوالات را حل کردید، پیشنهاد می‌کنیم مجددا روی مجموعه‌داده جدیدی که به دست آوردید، مدلسازی کنید تا تاثیر پیش‌پردازش را در نتیجه نهایی مشاهده کنید.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    برای انجام مدلسازی دوباره، فقط کافیست سلول زیر را اجرا کنید.
    <br>
    اگر اجرای این سلول با شکست مواجه شد، می‌تواند به یکی از دلایل زیر باشد.
</font>
</p>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    <ul>
        <li>
            کتابخانه Fast Auto ML را نصب نکرده باشید.
        </li>
        <li>
           پیش‌پردازش‌های توضیح داده‌شده را اشتباه انجام داده باشید.
        </li>
    </ul>
</font>
</div>

In [ ]:
model = AutoML(task='classification', time_budget=60, verbose=0)
cols_to_train = feature_importance[feature_importance.fi >= feature_importance.fi.quantile(.5)].index
x = df[cols_to_train]
y = df.label
model.fit(x,y)
x_train,x_test , y_train,y_test = train_test_split(x,y, random_state=313, test_size=.3, stratify=y)
y_pred = model.predict(x_test)
print(f'performance of model is {roc_auc_score(y_test, y_pred)}')

INFO:flaml.tune.searcher.blendsearch:No low-cost partial config given to the search algorithm. For cost-frugal search, consider providing low-cost values for cost-related hps via 'low_cost_partial_config'. More info can be found at https://microsoft.github.io/FLAML/docs/FAQ#about-low_cost_partial_config-in-tune
INFO:flaml.tune.searcher.blendsearch:No low-cost partial config given to the search algorithm. For cost-frugal search, consider providing low-cost values for cost-related hps via 'low_cost_partial_config'. More info can be found at https://microsoft.github.io/FLAML/docs/FAQ#about-low_cost_partial_config-in-tune

performance of model is 0.6030830107932912